export const ADD_ARTICLE = "ADD_ARTICLE";
export const MUTATE_SERIES_META = "MUTATE_SERIES_META";
export const TOGGLE_SERIES_VIS = "TOGGLE_SERIES_VIS";
export const CHANGE_SERIES_NAME = "CHANGE_SERIES_NAME";
export const ADD_DATA  = "ADD_DATA";
